### ISSUE TITLE
flterm: memory leak

### ISSUE THREAD

**Issue by jbqubit** [m-labs/misoc#66]
After running flterm on several ports to look for MiSoC BIOS messages my machine slows down. 

![image](https://user-images.githubusercontent.com/20543958/34013751-b7c400d2-e0e6-11e7-9a98-3eb9a51df210.png)

May be related to unplugging USB cable while continuing to run flterm.

**Comment by whitequark** [comment]
Yes, I've also seen flterm to hang in a busy loop. It's something related to asyncio, and the easiest way to reproduce is to run an flterm instance in the background and then another on the same port.

**Comment by jonaskeller** [comment]
Not sure if this is related, but running just a single instance on windows consumes about 8GB/h before eventually crashing:

	>python -m misoc.tools.flterm com4  1>>uart_corelog
	Traceback (most recent call last):
	  File "C:\Anaconda3\envs\artiq3.4\lib\runpy.py", line 193, in _run_module_as_main
		"__main__", mod_spec)
	  File "C:\Anaconda3\envs\artiq3.4\lib\runpy.py", line 85, in _run_code
		exec(code, run_globals)
	  File "C:\Anaconda3\envs\artiq3.4\lib\site-packages\misoc\tools\flterm.py", line 294, in <module>
		main()
	  File "C:\Anaconda3\envs\artiq3.4\lib\site-packages\misoc\tools\flterm.py", line 286, in main
		loop.run_until_complete(flterm.main_task)
	  File "C:\Anaconda3\envs\artiq3.4\lib\asyncio\base_events.py", line 467, in run_until_complete
		return future.result()
	  File "C:\Anaconda3\envs\artiq3.4\lib\asyncio\futures.py", line 294, in result
		raise self._exception
	  File "C:\Anaconda3\envs\artiq3.4\lib\asyncio\tasks.py", line 240, in _step
		result = coro.send(None)
	  File "C:\Anaconda3\envs\artiq3.4\lib\site-packages\misoc\tools\flterm.py", line 238, in main_coro
		await self.port.write(fs[1].result())
	  File "C:\Anaconda3\envs\artiq3.4\lib\asyncio\futures.py", line 294, in result
		raise self._exception
	  File "C:\Anaconda3\envs\artiq3.4\lib\asyncio\tasks.py", line 240, in _step
		result = coro.send(None)
	  File "C:\Anaconda3\envs\artiq3.4\lib\asyncio\queues.py", line 164, in get
		getter = self._loop.create_future()
	  File "C:\Anaconda3\envs\artiq3.4\lib\asyncio\base_events.py", line 275, in create_future
		return futures.Future(loop=self)
	  File "C:\Anaconda3\envs\artiq3.4\lib\asyncio\futures.py", line 171, in __init__
		self._loop = loop
	MemoryError

This is with misoc  0.9 py35_1+git2e2b7838

**Comment by sbourdeauducq** [comment]
@jonaskeller You can use this as an alternative: http://store.chipkin.com/articles/using-putty-for-serial-com-connections-hyperterminal-replacement
Speed is 115200.

**Comment by jonaskeller** [comment]
It still behaves the same on windows, so it looks like that's a separate bug.
It's not really an issue for me anymore though, thanks to the PuTTY alternative - thanks for pointing that out.

**Comment by whitequark** [comment]
Hm, I might have misdiagnosed it.

**Comment by sbourdeauducq** [comment]
I don't see how your commit could fix it.
1. it would be pretty hard to accumulate 8GB of serial data over a few hours, unless Python's ``bytes`` storage is extremely inefficient.
2. you are only resetting the buffer once when the magic string is found, then it accummulates again.

**Comment by whitequark** [comment]
Yes, you're right.
